- hosts: localhost

  tasks:

    - include_vars: common_vars.yml

    - name: patch ssh config to turn off known_hosts hashing
      lineinfile:
        dest={{ home_dir }}/.ssh/known_hosts
        regexp="{{ master_node_ip }}"
        state=absent
