- hosts: localhost

  vars:
    wait_for_min: 3

  tasks:

    - include_vars: common_vars.yml

    - name: add newly cloned vm as host
      add_host: name={{ master_node_ip }} groups=master_nodes ansible_ssh_user=root ansible_ssh_pass=r00tme #TODO parameterize


- hosts: master_nodes

  tasks:
    - name: preinstall packages
      yum: name={{ item }} state=present
      with_items:
        - wget
        - curl
        - rsync
      sudo: yes

    - name: download update script
      shell: "wget https://github.com/Mirantis/tools-sustaining/raw/master/scripts/mos_apply_mu.py"

    - name: execute update script
      shell: "python mos_apply_mu.py --update --all-envs --master-ip={{ master_node_ip }}"

    - name: wait for node updates to complete
      pause: minutes={{ wait_for_min }}          # TODO custom task for recurrent check

    - name: check update status
      shell: "python mos_apply_mu.py --check --all-envs --master-ip={{ master_node_ip }}"
